FROM ubuntu:20.04
RUN apt-get update && apt-get install -y && \
    apt-get install vim -y
RUN apt-get install wget -y

# install prometheus
RUN mkdir /opt/monitoring/
RUN wget -P /tmp/ https://github.com/prometheus/prometheus/releases/download/v2.28.0/prometheus-2.28.0.linux-amd64.tar.gz
RUN tar xvf /tmp/prometheus-2.28.0.linux-amd64.tar.gz --directory=/opt/monitoring/ --no-recursion
RUN mv /opt/monitoring/prometheus-2.28.0.linux-amd64/ /opt/monitoring/prometheus/
COPY ./prometheus/prometheus-custom.yml /opt/monitoring/prometheus/
RUN chmod +x /opt/monitoring/prometheus/*

CMD ["/opt/monitoring/prometheus/prometheus", "--config.file=/opt/monitoring/prometheus/prometheus-custom.yml"]
