{
 "title": "Overview Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "dashboardHostname",
    "label": "Filter by Hostname",
    "query": {
     "query": "label_values(cpu_utilization_percentage,hostname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Is Connected to vManage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_vmanage_is_connected{hostname=~\"$dashboardHostname\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "$dashboardHostname - Modem 2 Cellular Technology in Use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cellular_modem_radio_rat_selected{hostname=~\"$dashboardHostname\", name=\"Cellular0/2/0\"}",
     "legendFormat": "Modem 2"
    }
   ]
  },
  {
   "title": "$dashboardHostname - Modem 3 Cellular Technology in Use",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cellular_modem_radio_rat_selected{hostname=~\"$dashboardHostname\", name=\"Cellular0/2/0\"}",
     "legendFormat": "Modem 3"
    }
   ]
  },
  {
   "title": "$dashboardHostname Modem 2 Cellular Signal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         -15,
         0
        ],
        "type": "gt"
       },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         -83,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "B" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         -108,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "ne"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "ne"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "B" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "ne"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "$dashboardHostname Modem 3 Cellular Signal",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         -15,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "when" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         -83,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "B" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         -108,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "ne"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "ne"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "B" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "ne"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "$dashboardHostname - G0/0/0 WAN Connectivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "$dashboardHostname - Modem 2 WAN Connectivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "$dashboardHostname - Modem 3 WAN Connectivity",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "A" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      },
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": { "params": [ "C" ] },
       "reducer": {
        "params": [],
        "type": "last"
       },
       "type": "query"
      }
     ],
     "type": "classic_conditions"
    }
   ]
  },
  {
   "title": "$dashboardHostname - CPU Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_utilization_percentage{hostname=~\"$dashboardHostname\"}",
     "legendFormat": "{{hostname}} CPU {{time_period}} Utilization Percentage"
    }
   ]
  },
  {
   "title": "$dashboardHostname - Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_pool_percent_used{hostname=~\"$dashboardHostname\", name=\"Processor\"}",
     "legendFormat": "{{hostname}} Memory Utilization Percentage"
    }
   ]
  },
  {
   "title": "Interface Operational Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "intf_stats_operational_status{hostname=~\"$dashboardHostname\", name=~\"GigabitEthernet0/1/0|GigabitEthernet0/1/1|GigabitEthernet0/1/2|GigabitEthernet0/1/3\"}",
     "legendFormat": "{{hostname}} - {{name}}"
    }
   ]
  }
 ]
}