{
 "title": "Cellular Modem Statistics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cellular Modem Statistics - Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cellular_modem_radio_rsrp{name!~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} RSRP"
    },
    {
     "expr": "cellular_modem_radio_rsrq{name!~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} RSRQ"
    },
    {
     "expr": "cellular_modem_radio_rssi{name!~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} RSSI"
    },
    {
     "expr": "cellular_modem_radio_snr{name=~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} SNR"
    }
   ]
  },
  {
   "title": "Cellular Modem Statistics - RSRQ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cellular_modem_radio_rsrq{name!~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} RSRQ"
    }
   ]
  },
  {
   "title": "Interface States",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    { "expr": "intf_stats_operational_status", "legendFormat": "{{name}} Oper-Status" }
   ]
  },
  {
   "title": "Cellular Modem Statistics - RSSI",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cellular_modem_radio_rssi{name!~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} RSSI"
    }
   ]
  },
  {
   "title": "Device Resource Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "memory_pool_percent_used{name=\"Processor\"}",
     "legendFormat": "{{hostname}} Memory Utilization Percentage"
    },
    {
     "expr": "cpu_utilization_percentage",
     "legendFormat": "{{hostname}} CPU {{time_period}} Utilization Percentage"
    }
   ]
  },
  {
   "title": "Cellular Modem Statistics - RSRP",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cellular_modem_radio_rsrp{name!~\"Cellular0/2/1|Cellular0/3/1\"}",
     "legendFormat": "{{name}} RSRP"
    }
   ]
  }
 ]
}